spring.datasource.url=jdbc:mariadb://localhost:3306/${SMARTLOCK_DATABASE}
spring.datasource.username=${SMARTLOCK_USER}
spring.datasource.password=${SMARTLOCK_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true