spring.application.name=smartlock-platform

# Default to development when no explicit profile is provided.
spring.profiles.default=dev

# Shared Spring DataSource Configuration
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7

# Elements take their values from maven pom.xml build-related information
documentation.application.description=Security platform
documentation.application.version=1.0.0

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8
